// The complete set of valid IANA/legacy timezone names, per
// https://en.wikipedia.org/wiki/List_of_tz_database_time_zones — isolated in
// its own file so the bulky table stays out of the timezone logic
// (helpers/timezones.js). Used to validate any timezone name scraped from page
// text/scripts before using it as an event's `ctz`.
//
// DOM-free. Augments globalThis.GCal (never replaces it) so load order can't
// clobber another file's contributions.
globalThis.GCal = Object.assign(globalThis.GCal || {}, {
  VALID_TIMEZONES: new Set([
    "Atlantic/Cape_Verde", "Africa/Abidjan", "Africa/Bissau", "Africa/Monrovia", "Africa/Sao_Tome", "Africa/Casablanca", "Africa/El_Aaiun", "Africa/Algiers",
    "Africa/Lagos", "Africa/Ndjamena", "Africa/Tunis", "Africa/Johannesburg", "Africa/Juba", "Africa/Khartoum", "Africa/Maputo", "Africa/Tripoli",
    "Africa/Windhoek", "Africa/Cairo", "Africa/Nairobi", "Indian/Mauritius", "Antarctica/Rothera", "Antarctica/Troll", "Antarctica/Mawson", "Antarctica/Vostok",
    "Antarctica/Davis", "Antarctica/Casey", "Asia/Beirut", "Asia/Famagusta", "Asia/Gaza", "Asia/Hebron", "Asia/Jerusalem", "Asia/Nicosia",
    "Asia/Amman", "Asia/Baghdad", "Asia/Damascus", "Asia/Qatar", "Asia/Riyadh", "Asia/Tehran", "Asia/Baku", "Asia/Dubai",
    "Asia/Tbilisi", "Asia/Yerevan", "Asia/Kabul", "Asia/Almaty", "Asia/Aqtobe", "Asia/Aqtau", "Asia/Ashgabat", "Asia/Atyrau",
    "Asia/Dushanbe", "Asia/Karachi", "Indian/Maldives", "Asia/Oral", "Asia/Qostanay", "Asia/Qyzylorda", "Asia/Samarkand", "Asia/Tashkent",
    "Asia/Colombo", "Asia/Kolkata", "Asia/Kathmandu", "Asia/Bishkek", "Indian/Chagos", "Asia/Dhaka", "Asia/Thimphu", "Asia/Urumqi",
    "Asia/Yangon", "Asia/Bangkok", "Asia/Ho_Chi_Minh", "Asia/Hovd", "Asia/Jakarta", "Asia/Pontianak", "Asia/Hong_Kong", "Asia/Kuching",
    "Asia/Macau", "Asia/Makassar", "Asia/Manila", "Asia/Shanghai", "Asia/Singapore", "Asia/Taipei", "Asia/Ulaanbaatar", "Asia/Dili",
    "Asia/Jayapura", "Asia/Pyongyang", "Asia/Seoul", "Asia/Tokyo", "Pacific/Niue", "Pacific/Pago_Pago", "Pacific/Rarotonga", "Pacific/Tahiti",
    "Pacific/Marquesas", "Pacific/Gambier", "Pacific/Pitcairn", "Australia/Perth", "Australia/Eucla", "Pacific/Palau", "Australia/Darwin", "Australia/Adelaide",
    "Australia/Broken_Hill", "Australia/Brisbane", "Pacific/Guam", "Australia/Lindeman", "Pacific/Port_Moresby", "Australia/Hobart", "Antarctica/Macquarie", "Australia/Melbourne",
    "Australia/Sydney", "Australia/Lord_Howe", "Pacific/Bougainville", "Pacific/Efate", "Pacific/Guadalcanal", "Pacific/Kosrae", "Pacific/Noumea", "Pacific/Norfolk",
    "Pacific/Fiji", "Pacific/Kwajalein", "Pacific/Nauru", "Pacific/Tarawa", "Pacific/Auckland", "Pacific/Chatham", "Pacific/Apia", "Pacific/Fakaofo",
    "Pacific/Kanton", "Pacific/Tongatapu", "Pacific/Kiritimati", "US/Samoa", "Pacific/Samoa", "Pacific/Midway", "US/Hawaii", "Pacific/Johnston",
    "HST", "US/Aleutian", "America/Atka", "US/Alaska", "US/Pacific", "PST8PDT", "Mexico/BajaNorte", "America/Ensenada",
    "America/Santa_Isabel", "Mexico/BajaSur", "MST", "US/Arizona", "America/Creston", "Canada/Pacific", "Canada/Yukon", "MST7MDT",
    "Navajo", "US/Mountain", "America/Shiprock", "Canada/Mountain", "America/Yellowknife", "Mexico/General", "Canada/Saskatchewan", "CST6CDT",
    "US/Central", "Chile/EasterIsland", "US/Indiana-Starke", "America/Knox_IN", "Canada/Central", "America/Rainy_River", "Jamaica", "EST",
    "America/Atikokan", "America/Cayman", "America/Coral_Harbour", "Brazil/Acre", "America/Porto_Acre", "US/Michigan", "Cuba", "US/East-Indiana",
    "America/Indianapolis", "America/Fort_Wayne", "America/Pangnirtung", "America/Louisville", "EST5EDT", "US/Eastern", "Canada/Eastern", "America/Nassau",
    "America/Montreal", "America/Nipigon", "America/Thunder_Bay", "Brazil/West", "America/Virgin", "America/Anguilla", "America/Antigua", "America/Aruba",
    "America/Blanc-Sablon", "America/Curacao", "America/Dominica", "America/Grenada", "America/Guadeloupe", "America/Kralendijk", "America/Lower_Princes", "America/Marigot",
    "America/Montserrat", "America/Port_of_Spain", "America/St_Barthelemy", "America/St_Kitts", "America/St_Lucia", "America/St_Thomas", "America/St_Vincent", "America/Tortola",
    "Canada/Atlantic", "Chile/Continental", "Canada/Newfoundland", "America/Buenos_Aires", "America/Catamarca", "America/Argentina/ComodRivadavia", "America/Cordoba", "America/Rosario",
    "America/Jujuy", "America/Mendoza", "Brazil/East", "Brazil/DeNoronha", "America/Godthab", "Etc/GMT+0", "Etc/GMT-0", "Etc/GMT0",
    "Etc/Greenwich", "GMT+0", "GMT-0", "GMT0", "Greenwich", "Etc/UCT", "Etc/Universal", "Etc/Zulu",
    "UCT", "UTC", "Universal", "Zulu", "Iceland", "Africa/Accra", "Africa/Bamako", "Africa/Banjul",
    "Africa/Conakry", "Africa/Dakar", "Africa/Freetown", "Africa/Lome", "Africa/Nouakchott", "Africa/Ouagadougou", "Atlantic/Reykjavik", "Atlantic/St_Helena",
    "Africa/Timbuktu", "Eire", "Atlantic/Faeroe", "Portugal", "WET", "GB", "GB-Eire", "Europe/Guernsey",
    "Europe/Isle_of_Man", "Europe/Jersey", "Europe/Belfast", "Africa/Bangui", "Africa/Brazzaville", "Africa/Douala", "Africa/Kinshasa", "Africa/Libreville",
    "Africa/Luanda", "Africa/Malabo", "Africa/Niamey", "Africa/Porto-Novo", "Europe/Ljubljana", "Europe/Podgorica", "Europe/Sarajevo", "Europe/Skopje",
    "Europe/Zagreb", "Arctic/Longyearbyen", "Europe/Copenhagen", "Europe/Oslo", "Europe/Stockholm", "Atlantic/Jan_Mayen", "CET", "MET",
    "Europe/Amsterdam", "Europe/Luxembourg", "Europe/Monaco", "Europe/Bratislava", "Europe/San_Marino", "Europe/Vatican", "Poland", "Europe/Busingen",
    "Europe/Vaduz", "Africa/Maseru", "Africa/Mbabane", "Africa/Blantyre", "Africa/Bujumbura", "Africa/Gaborone", "Africa/Harare", "Africa/Kigali",
    "Africa/Lubumbashi", "Africa/Lusaka", "Libya", "EET", "Egypt", "Europe/Tiraspol", "Europe/Mariehamn", "Israel",
    "Asia/Tel_Aviv", "Europe/Uzhgorod", "Europe/Zaporozhye", "Europe/Kiev", "Europe/Nicosia", "Turkey", "Asia/Istanbul", "W-SU",
    "Africa/Addis_Ababa", "Africa/Asmara", "Africa/Dar_es_Salaam", "Africa/Djibouti", "Africa/Kampala", "Africa/Mogadishu", "Indian/Antananarivo", "Indian/Comoro",
    "Indian/Mayotte", "Africa/Asmera", "Asia/Bahrain", "Antarctica/Syowa", "Asia/Aden", "Asia/Kuwait", "Iran", "Asia/Muscat",
    "Indian/Mahe", "Indian/Reunion", "Asia/Ashkhabad", "Indian/Kerguelen", "Asia/Calcutta", "Asia/Katmandu", "Asia/Dacca", "Asia/Thimbu",
    "Asia/Kashgar", "Indian/Cocos", "Asia/Rangoon", "Asia/Phnom_Penh", "Asia/Vientiane", "Indian/Christmas", "Asia/Saigon", "Hongkong",
    "Asia/Brunei", "Asia/Macao", "Asia/Ujung_Pandang", "Australia/West", "PRC", "Asia/Chongqing", "Asia/Harbin", "Asia/Chungking",
    "Singapore", "Asia/Kuala_Lumpur", "ROC", "Asia/Choibalsan", "Asia/Ulan_Bator", "ROK", "Japan", "Australia/North",
    "Australia/South", "Australia/Yancowinna", "Australia/Queensland", "Pacific/Saipan", "Antarctica/DumontDUrville", "Pacific/Chuuk", "Pacific/Yap", "Pacific/Truk",
    "Australia/Tasmania", "Australia/Currie", "Australia/Victoria", "Australia/ACT", "Australia/NSW", "Australia/Canberra", "Australia/LHI", "Pacific/Pohnpei",
    "Pacific/Ponape", "Kwajalein", "Pacific/Funafuti", "Pacific/Majuro", "Pacific/Wake", "Pacific/Wallis", "NZ", "Antarctica/McMurdo",
    "Antarctica/South_Pole", "NZ-CHAT", "Pacific/Enderbury", "America/Thule", "America/Nuuk", "America/Scoresbysund", "Atlantic/Azores", "America/Danmarkshavn",
    "Atlantic/Canary", "Europe/Dublin", "Atlantic/Faroe", "Europe/Lisbon", "Europe/London", "Atlantic/Madeira", "Europe/Andorra", "Europe/Belgrade",
    "Europe/Berlin", "Europe/Brussels", "Europe/Budapest", "Africa/Ceuta", "Europe/Gibraltar", "Europe/Madrid", "Europe/Malta", "Europe/Paris",
    "Europe/Prague", "Europe/Rome", "Europe/Tirane", "Europe/Vienna", "Europe/Warsaw", "Europe/Zurich", "Europe/Kaliningrad", "Europe/Athens",
    "Europe/Bucharest", "Europe/Chisinau", "Europe/Helsinki", "Europe/Kyiv", "Europe/Riga", "Europe/Sofia", "Europe/Tallinn", "Europe/Vilnius",
    "Europe/Istanbul", "Europe/Kirov", "Europe/Minsk", "Europe/Moscow", "Europe/Simferopol", "Europe/Volgograd", "Europe/Astrakhan", "Europe/Samara",
    "Europe/Saratov", "Europe/Ulyanovsk", "Asia/Yekaterinburg", "Asia/Omsk", "Asia/Barnaul", "Asia/Krasnoyarsk", "Asia/Novosibirsk", "Asia/Novokuznetsk",
    "Asia/Tomsk", "Asia/Irkutsk", "Asia/Chita", "Asia/Khandyga", "Asia/Yakutsk", "Asia/Ust-Nera", "Asia/Vladivostok", "Asia/Magadan",
    "Asia/Sakhalin", "Asia/Srednekolymsk", "Asia/Anadyr", "Asia/Kamchatka", "Factory", "Pacific/Honolulu", "America/Adak", "America/Anchorage",
    "America/Juneau", "America/Metlakatla", "America/Nome", "America/Sitka", "America/Yakutat", "America/Los_Angeles", "America/Tijuana", "America/Dawson_Creek",
    "America/Dawson", "America/Fort_Nelson", "America/Hermosillo", "America/Mazatlan", "America/Phoenix", "America/Vancouver", "America/Whitehorse", "America/Boise",
    "America/Cambridge_Bay", "America/Ciudad_Juarez", "America/Denver", "America/Edmonton", "America/Inuvik", "America/Bahia_Banderas", "America/Belize", "America/Chihuahua",
    "America/Costa_Rica", "America/El_Salvador", "America/Guatemala", "America/Managua", "America/Merida", "America/Mexico_City", "America/Monterrey", "America/Regina",
    "America/Swift_Current", "America/Tegucigalpa", "America/North_Dakota/Beulah", "America/North_Dakota/Center", "America/Chicago", "America/Indiana/Knox", "America/Matamoros", "America/Menominee",
    "America/North_Dakota/New_Salem", "America/Ojinaga", "America/Rankin_Inlet", "America/Resolute", "America/Indiana/Tell_City", "America/Winnipeg", "America/Cancun", "America/Jamaica",
    "America/Panama", "America/Detroit", "America/Grand_Turk", "America/Havana", "America/Indiana/Indianapolis", "America/Iqaluit", "America/Kentucky/Louisville", "America/Indiana/Marengo",
    "America/Kentucky/Monticello", "America/New_York", "America/Indiana/Petersburg", "America/Port-au-Prince", "America/Toronto", "America/Indiana/Vevay", "America/Indiana/Vincennes", "America/Indiana/Winamac",
    "America/Barbados", "America/Martinique", "America/Puerto_Rico", "America/Santo_Domingo", "Atlantic/Bermuda", "America/Glace_Bay", "America/Goose_Bay", "America/Halifax",
    "America/Moncton", "America/St_Johns", "America/Miquelon", "Pacific/Galapagos", "Pacific/Easter", "America/Bogota", "America/Eirunepe", "America/Guayaquil",
    "America/Lima", "America/Rio_Branco", "America/Boa_Vista", "America/Campo_Grande", "America/Caracas", "America/Cuiaba", "America/Guyana", "America/La_Paz",
    "America/Manaus", "America/Porto_Velho", "America/Santiago", "America/Araguaina", "America/Asuncion", "America/Bahia", "America/Belem", "America/Argentina/Buenos_Aires",
    "America/Argentina/Catamarca", "America/Cayenne", "America/Argentina/Cordoba", "America/Coyhaique", "America/Fortaleza", "America/Argentina/Jujuy", "America/Argentina/La_Rioja", "America/Maceio",
    "America/Argentina/Mendoza", "America/Montevideo", "Antarctica/Palmer", "America/Paramaribo", "America/Punta_Arenas", "America/Recife", "America/Argentina/Rio_Gallegos", "America/Argentina/Salta",
    "America/Argentina/San_Juan", "America/Argentina/San_Luis", "America/Santarem", "America/Sao_Paulo", "Atlantic/Stanley", "America/Argentina/Tucuman", "America/Argentina/Ushuaia", "America/Noronha",
    "Atlantic/South_Georgia",
  ]),
});
