package checks

import (
	"path"
	"regexp"
	"strings"

	"claudinite.com/checksdk"
)

// Every artifact `npm run regen` rewrites carries a merge=ours entry in
// .gitattributes, so a conflicting merge keeps one side and the generator
// is rerun. Requirement kinds are auto-discovered, so a new image kind's
// baselines appear with nobody editing the hand-kept list. This check
// takes the UI snapshots and the lowercase `.generated.` artifacts; the
// uppercase GENERATED names are the canon's generated-merge-driver's half.
// Only the artifact-with-no-entry direction is checked.
const regenWhy = "a regen artifact off the `ours` driver hits a hand-resolved merge conflict — and the UI " +
	"baselines are binary PNGs git cannot 3-way merge at all"

var (
	// caseSnapshot is dev/requirements/<kind>/cases/<case>.png, any kind.
	caseSnapshot  = regexp.MustCompile(`^dev/requirements/[^/]+/cases/[^/]+\.png$`)
	lowerMarker   = regexp.MustCompile(`\.generated\.`)
	mergeOursWord = regexp.MustCompile(`\bmerge=ours\b`)
)

func init() {
	checksdk.Register(checksdk.Check{
		ID:   "regen-artifacts-merge-ours",
		Tags: []string{"world"},
		Doc:  doc,
		Why:  regenWhy,
		Run:  regenArtifactsMergeOurs,
	})
}

func isLowercaseGenerated(file string) bool {
	base := path.Base(file)
	return lowerMarker.MatchString(base) && !strings.Contains(base, "GENERATED")
}

// attrGlob is a gitignore-style .gitattributes pattern: `*` and `?` stay
// inside one segment, `**` crosses them.
func attrGlob(glob string) *regexp.Regexp {
	var b strings.Builder
	for i := 0; i < len(glob); i++ {
		switch c := glob[i]; {
		case c == '*' && i+1 < len(glob) && glob[i+1] == '*':
			b.WriteString(".*")
			i++
		case c == '*':
			b.WriteString("[^/]*")
		case c == '?':
			b.WriteString("[^/]")
		case strings.IndexByte(`.+^${}()|[]\`, c) >= 0:
			b.WriteByte('\\')
			b.WriteByte(c)
		default:
			b.WriteByte(c)
		}
	}
	re, err := regexp.Compile("^" + b.String() + "$")
	if err != nil {
		return regexp.MustCompile(`$.^`)
	}
	return re
}

type oursPattern struct {
	re         *regexp.Regexp
	byBasename bool
}

// oursPatterns are the patterns of .gitattributes' merge=ours lines; one
// with no slash matches by basename at any depth.
func oursPatterns(text string) []oursPattern {
	var out []oursPattern
	for _, l := range strings.Split(text, "\n") {
		l = strings.TrimSpace(l)
		if l == "" || strings.HasPrefix(l, "#") || !mergeOursWord.MatchString(l) {
			continue
		}
		p := strings.TrimLeft(fields(l)[0], "/")
		out = append(out, oursPattern{attrGlob(p), !strings.Contains(p, "/")})
	}
	return out
}

func regenArtifactsMergeOurs(repo checksdk.Repo) []checksdk.Finding {
	// AllFiles: this check reasons about generated artifacts, so it must
	// see them even if the repo marks them linguist-generated.
	var artifacts []string
	for _, f := range repo.AllFiles() {
		if caseSnapshot.MatchString(f) || isLowercaseGenerated(f) {
			artifacts = append(artifacts, f)
		}
	}
	if len(artifacts) == 0 {
		return nil
	}
	attrs, _ := repo.Read(".gitattributes")
	patterns := oursPatterns(attrs)

	var out []checksdk.Finding
	for _, file := range artifacts {
		base := path.Base(file)
		covered := false
		for _, p := range patterns {
			subject := file
			if p.byBasename {
				subject = base
			}
			if p.re.MatchString(subject) {
				covered = true
				break
			}
		}
		if covered {
			continue
		}
		// The shape the repo already uses: one line per snapshot
		// directory, one per generated file.
		suggestion := file
		if caseSnapshot.MatchString(file) {
			suggestion = path.Dir(file) + "/*.png"
		}
		out = append(out, checksdk.Finding{
			Path:     file,
			Sentence: file + " is regenerated by `npm run regen` but has no merge=ours entry in .gitattributes",
			Fix:      "add `" + suggestion + " merge=ours` to .gitattributes (beside the other regen artifacts), so a conflicting merge auto-resolves and you rerun the generator instead of hand-merging",
		})
	}
	return out
}
