// Builds test/ui/README.md — the reviewable gallery of the UI snapshots: every
// case's image with its description and the uiRequirements it checks, so the
// current (or changed) popup state shows in GitHub's folder/diff viewer.
//
// It's DERIVED from the cases (loadCases gives { name, description, requirements }
// per test/ui/cases/<name>.case.js), so there's no hand-maintained copy to drift:
// `npm run refresh:ui` regenerates it alongside the PNGs, and readme.test.js
// asserts the committed file matches (a read-only gate in CI). Output is
// deterministic — no timestamps — so an unchanged run yields no diff. (The
// spec-to-snapshot coverage itself is enforced by
// test/uber/ui-requirements-coverage.test.js, not restated here.)
//
// NOTE: this is an autogenerated file but intentionally NOT named
// *.GENERATED.md (the repo's usual cue): GitHub only auto-renders a file literally
// named README.md as a folder's landing page, which is the whole point of this
// gallery. The do-not-edit banner in the output + the CI gate stand in for the
// GENERATED filename.
"use strict";

const path = require("node:path");
const { loadCases } = require("./cases");

const README_PATH = path.join(__dirname, "README.md");

const HEADER = `# UI snapshots

> **Generated file — do not edit by hand.** Run \`npm run refresh:ui\` to
> regenerate; \`test/ui/readme.test.js\` fails if it drifts.

Each popup state is a self-contained case in [\`cases/\`](cases/): a
\`<name>.case.js\` module supplying only *fake data* and the list of
[\`uiRequirements.md\`](../../docs/uiRequirements.md) IDs it checks, paired with
its reference \`<name>.png\`. The renderer feeds that data to \`ui/popup.js\`'s
real \`render()\` — the same \`chooseContent\` + views the extension runs — and
rasterizes the result, so these images track the shipped popup directly. See
[\`docs/claude/testing.md\`](../../docs/claude/testing.md) for the mechanics.

A case names its scenario and expectation and bundles several requirements into
one image. Every leaf requirement is covered by at least one case, enforced by
\`test/uber/ui-requirements-coverage.test.js\`.
`;

// "1.10" sorts after "1.9" numerically, not lexically — order each case's
// requirement list by its dotted numeric segments so it reads like the spec.
function byNumericId(a, b) {
  const pa = a.split(".").map(Number);
  const pb = b.split(".").map(Number);
  for (let i = 0; i < Math.max(pa.length, pb.length); i++) {
    const d = (pa[i] || 0) - (pb[i] || 0);
    if (d) return d;
  }
  return 0;
}

function gallerySection({ name, description, requirements }) {
  const reqs = (requirements || []).slice().sort(byNumericId).map((id) => `\`${id}\``).join(", ");
  const reqLine = reqs ? `Requirements: ${reqs}\n\n` : "";
  return `## ${name}\n\n${description}\n\n${reqLine}![${name}](cases/${name}.png)\n`;
}

function buildReadme() {
  const sections = loadCases().map(gallerySection);
  return `${HEADER}\n${sections.join("\n")}`;
}

module.exports = { buildReadme, README_PATH };
