// Builds test/ui/README.md — the reviewable gallery of the UI snapshots: every
// case's image with its description and the uiRequirements it checks, plus a
// coverage map (every requirement -> the case(s) that cover it), so the current
// (or changed) popup state AND the spec-to-snapshot traceability both show in
// GitHub's folder/diff viewer.
//
// It's DERIVED from the cases (loadCases gives { name, description, requirements }
// per test/ui/cases/<name>.case.js) and docs/uiRequirements.md (the requirement
// list), so there's no hand-maintained copy to drift: `npm run refresh:ui`
// regenerates it alongside the PNGs, and readme.test.js asserts the committed file
// matches (a read-only gate in CI). Output is deterministic — no timestamps — so
// an unchanged run yields no diff.
//
// NOTE: this is an autogenerated file but intentionally NOT named
// *.GENERATED.md (the repo's usual cue): GitHub only auto-renders a file literally
// named README.md as a folder's landing page, which is the whole point of this
// gallery. The do-not-edit banner in the output + the CI gate stand in for the
// GENERATED filename.
"use strict";

const path = require("node:path");
const { loadCases } = require("./cases");
const { leafRequirementIds } = require("./ui-requirements");

const README_PATH = path.join(__dirname, "README.md");

const HEADER = `# UI snapshots

> **Generated file — do not edit by hand.** Run \`npm run refresh:ui\` to
> regenerate; \`test/ui/readme.test.js\` fails if it drifts.

Each popup state is a self-contained case in [\`cases/\`](cases/): a
\`<name>.case.js\` module supplying only *fake data* and the list of
[\`uiRequirements.md\`](../../docs/uiRequirements.md) IDs it checks, paired with
its reference \`<name>.png\`. The renderer feeds that data to \`ui/popup.js\`'s
real \`render()\` — the same \`chooseContent\` + views the extension runs — and
rasterizes the result, so these images track the shipped popup directly. See
[\`docs/claude/testing.md\`](../../docs/claude/testing.md) for the mechanics.

A case names its scenario and expectation and bundles several requirements into
one image. Every leaf requirement is covered by at least one case, enforced by
\`test/uber/ui-requirements-coverage.test.js\`; the coverage map below is the
generated proof.
`;

// "1.10" sorts after "1.9" numerically, not lexically — order the coverage map
// by each ID's dotted numeric segments so it reads like the spec.
function byNumericId(a, b) {
  const pa = a.split(".").map(Number);
  const pb = b.split(".").map(Number);
  for (let i = 0; i < Math.max(pa.length, pb.length); i++) {
    const d = (pa[i] || 0) - (pb[i] || 0);
    if (d) return d;
  }
  return 0;
}

function coverageTable(cases) {
  const by = new Map(leafRequirementIds().map((id) => [id, []]));
  for (const c of cases) {
    for (const id of c.requirements || []) {
      if (by.has(id)) by.get(id).push(c.name);
    }
  }
  const rows = [...by.keys()].sort(byNumericId).map((id) => {
    const names = by.get(id);
    return `| \`${id}\` | ${names.length ? names.join("<br>") : "—"} |`;
  });
  return `## Requirement coverage\n\nEvery leaf requirement in [\`docs/uiRequirements.md\`](../../docs/uiRequirements.md), and the case(s) that check it.\n\n| Requirement | Covered by |\n| --- | --- |\n${rows.join("\n")}\n`;
}

function gallerySection({ name, description, requirements }) {
  const reqs = (requirements || []).slice().sort(byNumericId).map((id) => `\`${id}\``).join(", ");
  const reqLine = reqs ? `Requirements: ${reqs}\n\n` : "";
  return `## ${name}\n\n${description}\n\n${reqLine}![${name}](cases/${name}.png)\n`;
}

function buildReadme() {
  const cases = loadCases();
  const sections = cases.map(gallerySection);
  return `${HEADER}\n${coverageTable(cases)}\n${sections.join("\n")}`;
}

module.exports = { buildReadme, README_PATH };
