#!/usr/bin/env node
// Generates two derived files from the pipeline sources on disk:
//   - pipeline/load-order.generated.json — the single source of truth for the
//     order the extraction-pipeline files are injected into the page (and
//     exercised by the tests).
//   - pipeline/worker-imports.generated.js — the registry + every source's
//     matcher, as an importScripts() call the background service worker
//     (ui/toolbar-icon.js) loads at startup. Generated (not hand-listed) so
//     adding a source touches no file in ui/ and never conflicts there.
// Run it with `npm run index` after adding/removing a source or pipeline file.
//
// Adding a source is a single-new-file change: drop pipeline/sources/<site>.js
// and rerun this; both lists are regenerated mechanically rather than kept in
// sync by hand. A CI test (test/unit/load-order-generated.test.js) asserts the
// committed files match what this generator would produce, so they can never
// silently drift.
//
// Ordering rule (the only ordering that matters): the registry and shared
// helpers load FIRST (they build globalThis.GCal), the orchestrator
// (assemble-events.js) loads LAST (its completion value is the extraction
// result), and everything in between — the extract-* layers and the per-source
// files — is sorted for a stable, conflict-free list.

"use strict";

const fs = require("node:fs");
const path = require("node:path");

const ROOT = path.join(__dirname, "..");
const DIR = "pipeline";
const OUTPUT = "pipeline/load-order.generated.json";
const WORKER_OUTPUT = "pipeline/worker-imports.generated.js";

const PINNED_FIRST = ["registry.js"]; // followed by helpers/*, added below
const PINNED_LAST = ["assemble-events.js"]; // the orchestrator
// Live in pipeline/ but are NOT injected into the page, so they're not part of
// the load order: build-calendar-url.js is loaded only by the popup document,
// and worker-imports.generated.js is THIS generator's own service-worker output
// (importScripts is undefined in a page, and it'd recursively list itself).
const NOT_INJECTED = ["build-calendar-url.js", "worker-imports.generated.js"];

const isJs = (f) => f.endsWith(".js");

function computeLoadOrder() {
  const helpers = fs
    .readdirSync(path.join(ROOT, DIR, "helpers"))
    .filter(isJs)
    .sort()
    .map((f) => `helpers/${f}`);

  const sources = fs
    .readdirSync(path.join(ROOT, DIR, "sources"))
    .filter(isJs)
    .map((f) => `sources/${f}`);

  const pinned = new Set([...PINNED_FIRST, ...PINNED_LAST, ...NOT_INJECTED]);
  const topLevelMiddle = fs
    .readdirSync(path.join(ROOT, DIR))
    .filter((f) => isJs(f) && !pinned.has(f)); // the extract-* layers

  const middle = [...topLevelMiddle, ...sources].sort();

  for (const f of [...PINNED_FIRST, ...PINNED_LAST]) {
    if (!fs.existsSync(path.join(ROOT, DIR, f))) {
      throw new Error(`expected ${DIR}/${f} to exist`);
    }
  }

  return [...PINNED_FIRST, ...helpers, ...middle, ...PINNED_LAST].map((f) => `${DIR}/${f}`);
}

// JSON, one path per line, trailing newline — a clean, reviewable diff.
function render(list) {
  return JSON.stringify(list, null, 2) + "\n";
}

// The subset the background service worker loads: the registry (builds GCal +
// isSupportedHost) plus every source's matcher, and nothing else — it never
// calls extract(), so it needs no helpers or orchestrator. Derived from the load
// order so it can't drift from the sources on disk.
function computeWorkerImports(loadOrder = computeLoadOrder()) {
  return loadOrder.filter(
    (f) => f === "pipeline/registry.js" || f.startsWith("pipeline/sources/")
  );
}

const WORKER_HEADER = `// GENERATED by \`npm run index\` (tools/index.js) — do not edit by hand.
//
// The MV3 background service worker (ui/toolbar-icon.js) importScripts THIS file
// at startup to load the registry + every source's matcher synchronously (MV3
// forbids the async read it would take to consult load-order.generated.json
// first). It's generated from the sources on disk, so adding a source touches no
// file in ui/ and this is never a merge-conflict surface; a drift guard
// (test/unit/load-order-generated.test.js) fails if it goes stale.
//
// Each path is extension-root absolute (leading slash). An importScripts path
// resolves relative to the worker's OWN dir (ui/), and these files live at the
// extension root, so the leading slash is what points there — without it the
// import resolves to ui/pipeline/… and aborts the worker (#146).
`;

// importScripts() with one extension-root-absolute path per line, no trailing
// comma — mirrors the hand-written block it replaces, for a clean diff.
function renderWorkerImports(paths) {
  const body = paths.map((p) => `  "/${p}"`).join(",\n");
  return `${WORKER_HEADER}importScripts(\n${body}\n);\n`;
}

if (require.main === module) {
  const list = computeLoadOrder();
  fs.writeFileSync(path.join(ROOT, OUTPUT), render(list));
  const workerImports = computeWorkerImports(list);
  fs.writeFileSync(path.join(ROOT, WORKER_OUTPUT), renderWorkerImports(workerImports));
  console.log(
    `Wrote ${OUTPUT} (${list.length} files) and ${WORKER_OUTPUT} (${workerImports.length} files)`
  );
}

module.exports = {
  computeLoadOrder,
  computeWorkerImports,
  render,
  renderWorkerImports,
  OUTPUT,
  WORKER_OUTPUT,
};
